"""Shared constants for category-classification runtime and evidence code."""
from __future__ import annotations

from pathlib import Path

MODEL_PATH = Path("data/models/classifier_latest.joblib")
REPORTS_DIR = Path("data/reports")
MODELS_DIR = Path("data/models")

MIN_PER_CLASS = 2
CONFIDENCE_THRESHOLDS = [0.0, 0.5, 0.55, 0.6, 0.7, 0.8, 0.9]
DEFAULT_ACCEPT_THRESHOLD = 0.55
DEFAULT_REVIEW_FLOOR = 0.25
EVIDENCE_THRESHOLD = DEFAULT_ACCEPT_THRESHOLD
TARGET_THRESHOLD_ACCURACY = 0.9
OTHER_CATEGORY = "other"

FEATURE_SETS = {"baseline", "feature_v2"}
DEFAULT_FEATURE_SET = "baseline"

MINIMUM_LABELLED_ROWS = 300
RECOMMENDED_LABELLED_ROWS = 800
IDEAL_LABELLED_ROWS = 2000
MINIMUM_PER_CATEGORY = 20
RECOMMENDED_PER_CATEGORY = 50
STRONG_PER_CATEGORY = 100

MIN_RETRAIN_LABELLED_ROWS = 8
CONFIDENCE_RECOMMENDATION_THRESHOLD = EVIDENCE_THRESHOLD
DEFAULT_RECOMMENDED_ESTIMATOR = "linear_svc_calibrated"
DEFAULT_RECOMMENDED_FEATURE_SET = "feature_v2"
CALIBRATED_ESTIMATORS = {"linear_svc_calibrated", "logreg"}
RETRAIN_LABEL_GROWTH_THRESHOLD = 0.20
RETRAIN_FEEDBACK_EVENTS_THRESHOLD = 25
RETRAIN_REJECTION_RATE_THRESHOLD = 0.35
RETRAIN_REJECTION_MIN_EVENTS = 10
