"""Transaction service facade used by FastAPI routers."""
from finance.transactions.export import CSV_COLUMNS, export_csv_lines, safe_csv_value
from finance.transactions.mutations import (
    UNCHANGED,
    InvalidCategoryAssignment,
    TransactionTypeDirectionMismatch,
    accept_suggestions,
    bulk_categorize,
    bulk_delete,
    delete_transaction,
    reject_suggestions,
    restore_suggestions,
    update_annotations,
    update_category,
    update_transaction_type,
)
from finance.transactions.queries import (
    filter_summary,
    filtered_transactions_stmt,
    list_transactions,
    matching_transactions,
    merchant_groups,
    merchant_groups_page,
    summary_by_category,
)
from finance.transactions.review import review_summary
from finance.transactions.types import (
    CategoryState,
    CategorySummary,
    FilterSummaryResult,
    MerchantAliasSuggestion,
    MerchantCandidate,
    MerchantCandidateVariant,
    MerchantGroupSortBy,
    MerchantGroupSummary,
    MerchantIdentity,
    RareClass,
    RecurringMerchant,
    ReviewCounts,
    TransactionFilters,
    TransactionSortBy,
    TransactionSortDirection,
)

__all__ = [
    "CSV_COLUMNS",
    "CategorySummary",
    "CategoryState",
    "FilterSummaryResult",
    "InvalidCategoryAssignment",
    "TransactionTypeDirectionMismatch",
    "MerchantAliasSuggestion",
    "MerchantCandidate",
    "MerchantCandidateVariant",
    "MerchantGroupSummary",
    "MerchantGroupSortBy",
    "MerchantIdentity",
    "RareClass",
    "RecurringMerchant",
    "ReviewCounts",
    "TransactionFilters",
    "TransactionSortBy",
    "TransactionSortDirection",
    "UNCHANGED",
    "accept_suggestions",
    "bulk_categorize",
    "bulk_delete",
    "delete_transaction",
    "export_csv_lines",
    "filter_summary",
    "filtered_transactions_stmt",
    "list_transactions",
    "matching_transactions",
    "merchant_groups",
    "merchant_groups_page",
    "reject_suggestions",
    "restore_suggestions",
    "review_summary",
    "safe_csv_value",
    "summary_by_category",
    "update_annotations",
    "update_category",
    "update_transaction_type",
]
